### ISSUE TITLE
[QST]

### ISSUE THREAD

**Issue by maitreya2048** [NVIDIA-Merlin/Transformers4Rec#362]
# ❓ Binary classification prediction task

## Details

Do you have any examples on how to use a binary classification prediction task? I am trying to leverage transformers4rec for a recommender model, but am trying to get the probability score for each item, so that I can recommend the argmax of the probabilities given by the model for all items. 
Does this integrate with the Trainer class? Since the output of this type of model is only a tensor, I get errors when using the Trainer class with a binaryClassificationTask prediction task.

**Comment by sararb** [comment]
Thank you for your questions! Please find below the related answers:

**Do you have any examples of how to use a binary classification prediction task?** 
—> We have some unit tests showing how to train a model with a binary classification task [here](https://github.com/NVIDIA-Merlin/Transformers4Rec/blob/8e270176f47ed3db6b7f949f51a7d62117de7209/tests/tf/model/test_model.py#L28). Note that the supported task is providing prediction at the session-level. Meaning for each sequence of interacted items we output one probability score. 

**Does this integrate with the Trainer class?**
—> Unfortunately, the current implementation of the Trainer class is only supporting the `NextItemPredictionTask` use-case. For any other use-case, you can use the base `fit` method as specified in this [test](https://github.com/NVIDIA-Merlin/Transformers4Rec/blob/8e270176f47ed3db6b7f949f51a7d62117de7209/tests/tf/model/test_model.py#L38) 


**I am trying to leverage transformers4rec for a recommender model, but am trying to get the probability score for each item so that I can recommend the argmax of the probabilities given by the model for all items.**
—> Could you give more details about the objective of your task:  Is it predicting the next item to recommend based on a softmax layer computing the probabilities over all possible item ids?

**Comment by benfred** [comment]
@maitreya2048 let us know if this was the info you're looking for!
