### ISSUE TITLE
[FEA] handling code-start problem on Transformers4rec

### ISSUE THREAD

**Issue by Ahanmr** [NVIDIA-Merlin/Transformers4Rec#363]
# 🚀 Feature request

* Hi, I was wondering if there's any current support in this library for handling cold-start problem? That is, adding newer products that's not already in the list/catalogue, and how can we handle this problem. 

* Second, is there a way to embed seasonality into the features for the transformer model that the model can use as a temporal features.

* Lastly, is there a way to use the embeddings of the transformer model from this library? ie, let's say the product_id and brand_id etc are features, currently I can see the text replaced by a token, but is there a way to access the embedding vector that this data is converted to as an input to the transformer model?

**Comment by sararb** [comment]
Hey Ahan! thank you for your questions! Please find below the related answers:

**I was wondering if there's any current support in this library for handling cold-start problem? That is, adding newer products that's not already in the list/catalogue, and how can we handle this problem.** 

—> In order to support the cold-start problem, we will need to handle the dynamic size of embeddings tables to add embeddings of newly seen items and also support a dynamic categorical encoding step where we can extend the vocabulary with these new items. Unfortunately, The current implementation of Transformers4Rec does not support variable size embedding tables. 
 
**Second, is there a way to embed seasonality into the features for the transformer model that the model can use as a temporal features.**
—> Do you mean add temporal features as additional inputs to the transformer model? If so, I believe it could be done during the pre-processing step by generating time-based features such as day of the week of the interactions, hour of the day, elapsed time to the previous interactions… The result of the processing returns the schema file with these additional features with an `item` tag to leverage them for each entry in the sequence. 

**Lastly, is there a way to use the embeddings of the transformer model from this library? ie, let's say the product_id and brand_id etc are features, currently, I can see the text replaced by a token, but is there a way to access the embedding vector that this data is converted to as an input to the transformer model?**
—> Yes, the model structure is organized as a sequence of the Input block, Transformer Block, and the prediction task. The first component (Input Block) is the one responsible for converting a raw `inputs`  (defined as a dictionary of sequences related to the item-features used: ids, category, brand …)  to one interaction embeddings sequence of shape (bs, seq_length, hidden_dim)  which will be then fed to the Transformer block. So to access this tensor you can call: 

```
interaction_embed_layer = model.heads[0].body[0]
embedding_tensor = interaction_embed_layer(inputs)
```

**Comment by Ahanmr** [comment]
I also had a follow-up question in the pre-processing part of the user-session data generation, so in column like product_id-list_seq, I have used max_length of sequence as 20, but there are many sequences that currently have length of only 3,4 or 5, I see that for such sequences, the product_id of last item is copied for rest of the sequence ( I believe similar to same padding) but I wanted to know if there was a way to replace it with 0, and if yes/no, based on the experiments performed, do you suggest I keep it in this manner:
1. product_id_list = [126, 484, 373, 373, 373, 373, 373, 373] or
2. product_id_list = [126, 484, 373, 0, 0, 0, 0, 0]

Wouldn't the model overfit in the first case if rest of the sequence is the same item, making the model predict the same value in the end? 

Secondly, I'm using NDCG, Recall, AP and Precision @ K metrics, I've been getting very low precision i.e, 0.06 or 0.08 whereas NDCG is very good in the range of 0.48-0.6, how is it possible that your precision is this low and NDCG and Average Precision are high, do you think I'm doing something wrong with my modelling here? @sararb 

<img width="460" alt="Screenshot 2022-02-14 at 4 38 21 AM" src="https://user-images.githubusercontent.com/26196002/153780175-aed6b87f-5d68-40e9-a1f8-f5a7cfd0da15.png">

**Comment by Ahanmr** [comment]
> interaction_embed_layer = model.heads[0].body[0]
embedding_tensor = interaction_embed_layer(inputs)

It says the ```inputs``` needs to be of the type dict to be usable here. But by default inputs are like this for me, is this not the input? :

```bash
TabularSequenceFeatures(
  (_aggregation): ConcatFeatures()
  (to_merge): ModuleDict(
    (continuous_module): ContinuousFeatures(
      (filter_features): FilterFeatures()
    )
    (categorical_module): SequenceEmbeddingFeatures(
      (filter_features): FilterFeatures()
      (embedding_tables): ModuleDict(
        (category_id-list_seq): Embedding(3103, 64, padding_idx=0)
        (brand-list_seq): Embedding(7385, 64, padding_idx=0)
        (product_id-list_seq): Embedding(1301974, 64, padding_idx=0)
      )
    )
  )
  (_masking): CausalLanguageModeling()
)
```

**Comment by Ahanmr** [comment]
Inputs need to be generated of this kind:

```bash
eval_dataload = get_dataloader(eval_data_paths, train_args.per_device_eval_batch_size)
batch = next(iter(eval_dataload))
batch
```

```bash
batch = {'item_id-list_seq': tensor([[  59, 1386,  244,    0,    0,    0,    0,    0,    0,    0,    0,    0,
             0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
             0,    0,    0,    0,    0,    0],
         [   2,    2,    2,    0,    0,    0,    0,    0,    0,    0,    0,    0,
             0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
             0,    0,    0,    0,    0,    0]],
'category_id-list_seq': tensor([[  59, 1386,  244,    0,    0,    0,    0,    0,    0,    0,    0,    0,
             0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
             0,    0,    0,    0,    0,    0],
         [   2,    2,    2,    0,    0,    0,    0,    0,    0,    0,    0,    0,
             0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
             0,    0,    0,    0,    0,    0]]
}
```

```bash
# access the embedding layer
interaction_embed_layer = model.heads[0].body[0]

# generate the embedding tensor by passing dict of inputs using dataloader
embedding_tensor = interaction_embed_layer(batch)

# Session - 1 --> Seq_len - 30 --> size of embeddings 256
print(embedding_tensor[0].shape)
embedding_tensor[0]
```
```bash
# item embedding output
torch.Size([30, 256])
tensor([[ 0.0103, -0.0112,  0.0143,  ..., -0.0075,  0.0337, -0.0152],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0851,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        ...,
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]],
       device='cuda:0', grad_fn=<SelectBackward0>)
```
