### ISSUE TITLE
[QST] Is there any example on how to "Sequential Recommendations"?

### ISSUE THREAD

**Issue by whoknowsB** [NVIDIA-Merlin/Transformers4Rec#385]
# ❓ Questions & Help

## Details
Following here: https://github.com/NVIDIA-Merlin/Transformers4Rec/discussions/384#discussion-3941348

**Comment by rnyak** [comment]
@whoknowsB hello. We do not have an example for Sequential Recommendations in our GH repo yet. Our examples are particularly on session-based models. you can easily adapt them for sequential recommendation. You can groupby by user_id instead of session_id, and create sequential interactions per user.

**Comment by rnyak** [comment]
@whoknowsB can we close this issue?
