### ISSUE TITLE
[QST] Understanding The Selection Of Feature In Schema File

### ISSUE THREAD

**Issue by SaadAhmed433** [NVIDIA-Merlin/Transformers4Rec#386]
# ❓ Questions & Help

Selection of feature key in the tutorial [here](https://github.com/NVIDIA-Merlin/Transformers4Rec/blob/de6f49420ef26000949864c40c5b90dec0e464b5/examples/tutorial/03-Session-based-recsys.ipynb) is confusing.

## Details
In this notebook here only one feature is selected in the schema variabe after loading the entire scheme file. Why is that?

![image](https://user-images.githubusercontent.com/98022049/158559642-c45a0fe9-e54b-4ff1-8e24-fc94054a0fab.png)

Dont we need the schema of other features so that they can become part of the input?

Please explain.

**Comment by rnyak** [comment]
@SaadAhmed433 if you notice the schema_tutorial.pb has more than one feature but we only select product -id column as input because in this example we only use one feature- simply product_id.

In the following cells you can see that we add side information so we leverage the other features in the `schema_tutorial.pb`.  We show users that schema file can have information on many features but you can use whatever feature you want to in your model. So, you dont need a schema for each feature because one schema file can have metadata for all features, and then you can select what features you want to use in your model with `select_by_name` method.  Hope that helps.

**Comment by SaadAhmed433** [comment]
Thank you! this really does help.
