### ISSUE TITLE
[FEA] Enhance transformer4rec to handle user "multi tenancy" issue

### ISSUE THREAD

**Issue by lightsailpro** [NVIDIA-Merlin/Transformers4Rec#429]
# 🚀 Feature request

Per sararb's suggestion in this issue https://github.com/NVIDIA-Merlin/Transformers4Rec/issues/426, please consider a new feature to handle the following "multi tenancy" challenges in modeling:

      A user can belong to a site (e.g. user category) in which users only interact with subset of global items. The top k recommendations/predictions should be from this subset of items only. But if we just train a global model, predict top k global items, then filter the prediction using the site id, the prediction will not be accurate for some small sites with limited set of items. Other options e.g. training of individual model for each site will be costly computing wise. Since transformer4rec can already handle item category. Please see if the model/framework can be adapted to handle the above user category/site context info. The model training for a user category or site should use the subset of items that belong to user's site. Prediction should be the same subset too. Ideally the the computing time should be reasonable e.g. close the training time of a single global model. 

## Motivation

This will be great feature, which can potentially reduce computing and training time of each site model. The issue may be similar to [GDMix model](https://github.com/linkedin/gdmix).

## Your contribution
I can potentially test and compare the metrics e.g. HR 10 of result from a global model and model with this enhanced feature.

**Comment by gabrielspmoreira** [comment]
I don't think this feature request will be eventually be implemented because training single model for sites with disjoint item sets will probably hurt the accuracy, lead to low performance during training and inference (due to the large resulting item catalog). I think you should look into ways to deploy and manage multiple small models with shared Triton Inference Server instances (which I am not expert on). I have added more detailed comments in your original discussion with @sararb in this issue #426 426
