### ISSUE TITLE
[QST] How to change categorical embeddings size?

### ISSUE THREAD

**Issue by antklen** [NVIDIA-Merlin/Transformers4Rec#515]
Hi! I can't find out how to control size of embeddings for categorical features. I create embeddings with TabularSequenceFeatures.from_schema and get embeddings with size 64. How to change this value?

**Comment by rnyak** [comment]
@antklen you can change the args here:

https://github.com/NVIDIA-Merlin/Transformers4Rec/blob/main/transformers4rec/torch/features/embedding.py#L105

the reason you get `64` is because the default  `embedding_dim_default` is set to `64`.  You can change that value, In addition,  you can set the  embedding_dims: Optional[Dict[str, int]]  as a dictionary (keys are feature names values are emb dims).  

let us know if you have further questions.

**Comment by antklen** [comment]
@rnyak thank you, this is complete answer to my question)
