### ISSUE TITLE
[FEA] Allow session_id / user_id to accept uuids or strings rather than just int.

### ISSUE THREAD

**Issue by dhollier** [NVIDIA-Merlin/Transformers4Rec#611]
# 🚀 Feature request

Allow session_id / user_id to accept uuids or strings rather than just int. 

## Motivation

I think its fairly common for sessions or users to be represented by uuids, but my understanding from the documentation is that currently Transformers4Rec only accepts ints for session_ids. It would be helpful if this limitation was removed so that session_ids would not have to be mapped to ints outside of the workflow.

**Comment by rnyak** [comment]
>that currently Transformers4Rec only accepts ints for session_ids.

This is not Transformers4rec related, you dont feed `session-id` to model so it wont affect model training. This is  related to`NVTabular` thing.  if you have long strings (long uuids), and you want to do groupby op with NVTabular that can be problematic due to cudf reasons. In that case you can try to use a smaller dataframe input.

But otherwise it should work. So you dont have to apply `categorify` to session id. Just remove the `session_id` from where you do ` ['col1, col2' col3]>> nvt.ops.Categorify()` and use ['session-id'] as it is.
