### ISSUE TITLE
[QST] Multi-task learning implementation question

### ISSUE THREAD

**Issue by nicoladisabato** [NVIDIA-Merlin/Transformers4Rec#645]
# ❓ Questions & Help

## Details

Hi, I'm trying to implement a session based rec sys using rees46 e-commerce dataset. 

I would like to implement a multi-task learning composed by:

- a **NextItemPredictionTask** for the next item id prediction on the session
- a "next category id prediction", maybe a multi-class classification task (?) for the next category id prediction.

I've done the NextItemPredictionTask following all the examples. 

Regarding the classification task, I only found the transformers4rec.torch.BinaryClassificationTask. Is there a solution for a next category prediction? Also with other approaches. 

Thank you so much.

**Comment by gabrielspmoreira** [comment]
Hi @nicoladisabato . I think your use case is valid, as multi-task learning of somewhat correlated tasks can typically improve models accuracy.
Transformers4Rec API offers an approach for basic multi-task learning by providing a list of tasks for the `Head` block like [here](test_model_with_multiple_heads_and_tasks):
```python
tasks = [
        tr.BinaryClassificationTask("classification"),
        tr.RegressionTask("regression"),
]
head_1 = tr.Head(body, tasks)
```

The `NextItemPredictionTask` uses the masking set in `TabularSequenceFeatures` (like [here](https://github.com/NVIDIA-Merlin/Transformers4Rec/blob/f5a0d422b96a3deefe0181da82a960141dfbf253/tests/unit/torch/model/test_model.py#L266-L275)) for identifying the item id column and creating the output layer (or reusing the item embedding table as output layer if `weight_tying=True`) for multi-class classification task of the next item id.

So we currently don't support having multiple `NextItemPredictionTask` in `Head`, each of them using a different target column, because they would be sharing the same `TabularSequenceFeatures`, where the masked labels will be the sequence of item ids.

P.s. if you want to create a single-task model for predicting the next category id, you would just need to change the dataset schema to tag the category id as "item_id" and remove that tag from the actual item id.

Maybe you could try to create your own prediction task based on `NextItemPredictionTask`, that supports predicting multiple sequential targets.

We have plans to refactor Transformers4Rec API in the future for better multi-task learning support of multiple sequence predictions.

**Comment by rnyak** [comment]
@nicoladisabato I am closing this ticket due to low activity. Please reopen if needed.
